version: '3'
services:
  web:
    restart: always
    build: .
    volumes:
      - ./:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    environment:
      NODE_ENV: 'development'
    ports:
      - '3000:3000'
    depends_on:
      - db
    links:
      - db
  db:
    image: 'mongo'
    container_name: 'mongo-database'
    volumes:
      - ./api/database
    ports:
      - '27017:27017'